/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.1 on Tue Jun  8 17:01:01 2010
 */

#include "sipAPIQtPoppler.h"


#line 346 "/usr/share/sip/PyQt4/QtCore/qdatetime.sip"
#include <qdatetime.h>
#line 13 "sipQtPopplerPoppler.cpp"


extern "C" {static PyObject *meth_Poppler_convertDate(PyObject *, PyObject *);}
static PyObject *meth_Poppler_convertDate(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        char * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "s", &a0))
        {
            QDateTime *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QDateTime(Poppler::convertDate(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QDateTime,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipParseErr, sipName_convertDate, NULL);

    return NULL;
}


static PyMethodDef methods_Poppler[] = {
    {SIP_MLNAME_CAST(sipName_convertDate), meth_Poppler_convertDate, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_QtPoppler_Poppler = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_NAMESPACE,
        sipNameNr_Poppler,
        {0}
    },
    {
        sipNameNr_Poppler,
        {0, 0, 1},
        1, methods_Poppler,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
