/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.1 on Tue Jun  8 17:01:01 2010
 */

#include "sipAPIQtPoppler.h"

#line 38 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 12 "sipQtPopplerQList0100PopplerFontInfo.cpp"

#line 45 "poppler-qt4.sip"
#define UNSTABLE_POPPLER_QT4 1
#include <qt4/poppler-qt4.h>
#line 17 "sipQtPopplerQList0100PopplerFontInfo.cpp"


extern "C" {static void assign_QList_0100Poppler_FontInfo(void *, SIP_SSIZE_T, const void *);}
static void assign_QList_0100Poppler_FontInfo(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QList<Poppler::FontInfo> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QList<Poppler::FontInfo> *>(sipSrc);
}


extern "C" {static void *array_QList_0100Poppler_FontInfo(SIP_SSIZE_T);}
static void *array_QList_0100Poppler_FontInfo(SIP_SSIZE_T sipNrElem)
{
    return new QList<Poppler::FontInfo>[sipNrElem];
}


extern "C" {static void *copy_QList_0100Poppler_FontInfo(const void *, SIP_SSIZE_T);}
static void *copy_QList_0100Poppler_FontInfo(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList<Poppler::FontInfo>(reinterpret_cast<const QList<Poppler::FontInfo> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0100Poppler_FontInfo(void *, int);}
static void release_QList_0100Poppler_FontInfo(void *ptr, int)
{
    Py_BEGIN_ALLOW_THREADS
    delete reinterpret_cast<QList<Poppler::FontInfo> *>(ptr);
    Py_END_ALLOW_THREADS
}



extern "C" {static int convertTo_QList_0100Poppler_FontInfo(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0100Poppler_FontInfo(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList<Poppler::FontInfo> **sipCppPtr = reinterpret_cast<QList<Poppler::FontInfo> **>(sipCppPtrV);

#line 69 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    SIP_SSIZE_T len;

    // Check the type if that is all that is required.
    if (sipIsErr == NULL)
    {
        if (!PySequence_Check(sipPy) || (len = PySequence_Size(sipPy)) < 0)
            return 0;

        for (SIP_SSIZE_T i = 0; i < len; ++i)
        {
            PyObject *itm = PySequence_ITEM(sipPy, i);
            bool ok = (itm && sipCanConvertToType(itm, sipType_Poppler_FontInfo, SIP_NOT_NONE));

            Py_XDECREF(itm);

            if (!ok)
                return 0;
        }

        return 1;
    }

    QList<Poppler::FontInfo> *ql = new QList<Poppler::FontInfo>;
    len = PySequence_Size(sipPy);
 
    for (SIP_SSIZE_T i = 0; i < len; ++i)
    {
        PyObject *itm = PySequence_ITEM(sipPy, i);
        int state;
        Poppler::FontInfo *t = reinterpret_cast<Poppler::FontInfo *>(sipConvertToType(itm, sipType_Poppler_FontInfo, sipTransferObj, SIP_NOT_NONE, &state, sipIsErr));

        Py_DECREF(itm);
 
        if (*sipIsErr)
        {
            sipReleaseType(t, sipType_Poppler_FontInfo, state);

            delete ql;
            return 0;
        }

        ql->append(*t);

        sipReleaseType(t, sipType_Poppler_FontInfo, state);
    }
 
    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 107 "sipQtPopplerQList0100PopplerFontInfo.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0100Poppler_FontInfo(void *, PyObject *);}
static PyObject *convertFrom_QList_0100Poppler_FontInfo(void *sipCppV,PyObject *sipTransferObj)
{
   QList<Poppler::FontInfo> *sipCpp = reinterpret_cast<QList<Poppler::FontInfo> *>(sipCppV);

#line 42 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    // Create the list.
    PyObject *l;

    if ((l = PyList_New(sipCpp->size())) == NULL)
        return NULL;

    // Set the list elements.
    for (int i = 0; i < sipCpp->size(); ++i)
    {
        Poppler::FontInfo *t = new Poppler::FontInfo(sipCpp->at(i));
        PyObject *tobj;

        if ((tobj = sipConvertFromNewType(t, sipType_Poppler_FontInfo, sipTransferObj)) == NULL)
        {
            Py_DECREF(l);
            delete t;

            return NULL;
        }

        PyList_SET_ITEM(l, i, tobj);
    }

    return l;
#line 141 "sipQtPopplerQList0100PopplerFontInfo.cpp"
}


sipMappedTypeDef sipTypeDef_QtPoppler_QList_0100Poppler_FontInfo = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_292,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0100Poppler_FontInfo,
    array_QList_0100Poppler_FontInfo,
    copy_QList_0100Poppler_FontInfo,
    release_QList_0100Poppler_FontInfo,
    convertTo_QList_0100Poppler_FontInfo,
    convertFrom_QList_0100Poppler_FontInfo
};
